apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: suadeo-application
  namespace: suadeo-dev
spec:
  project: default

  source:
    repoURL: https://github.com/dnum-mi/suadeo-test-argocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: suadeo-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

 