apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
  namespace: echoserver-ns
spec:
  replicas: 8
  selector:
    matchLabels:
      app: echoserver-application
  template:
    metadata:
      labels:
        app: echoserver-application
    spec:
      containers:
      #- image: opsdockerimage/echoserver:1.10 
      #- image: nginxdemos/hello:0.3
      #- image: hashicorp/http-echo
      #- image: odeo/rootless-nginx
      #- image: quay.io/powercloud/http-echo
      #- image: nginxinc/nginx-unprivileged
      #- image: docker.io/tobicolin/echo-server-rootless:1.0.0
      - image: quay.io/redhattraining/hello-world-nginx
      
        imagePullPolicy: Always
        name: echoserver-application
        ports:
        - containerPort: 8080
