apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: echoserver-ns
  name: echoserver-ingress

spec:
  rules:
  - host: "echo.fake-domain.local" 
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name:  echoserver-service
              port:
                  number: 8080
